-- triggeur pour JEU
CREATE TRIGGER JEU_ID_TRG
BEFORE INSERT
ON JEU
FOR EACH ROW
BEGIN
    SELECT JEU_SEQ.NEXTVAL
    INTO :NEW.IdJeu
    FROM DUAL;
END;
/
-- triggeur pour CONTENU
CREATE TRIGGER CONTENU_ID_TRG
BEFORE INSERT
ON CONTENU
FOR EACH ROW
BEGIN
    SELECT CONTENU_SEQ.NEXTVAL
    INTO :NEW.IdContenu
    FROM DUAL;
END;
/
-- triggeur pour SUCCES
CREATE TRIGGER SUCCES_ID_TRG
BEFORE INSERT
ON SUCCES
FOR EACH ROW
BEGIN
    SELECT SUCCES_SEQ.NEXTVAL
    INTO :NEW.IdSucces
    FROM DUAL;
END;
/
-- triggeur pour SUCCES
CREATE TRIGGER PERIODE_ID_TRG
BEFORE INSERT
ON PERIODE
FOR EACH ROW
BEGIN
    SELECT PERIODE_SEQ.NEXTVAL
    INTO :NEW.IdPeriode
    FROM DUAL;
END;
/
-- triggeur pour SUCCES
CREATE TRIGGER JOUEUR_ID_TRG
BEFORE INSERT
ON JOUEUR
FOR EACH ROW
BEGIN
    SELECT JOUEUR_SEQ.NEXTVAL
    INTO :NEW.NoJoueur
    FROM DUAL;
END;
/
-- triggeur pour SUCCES
CREATE TRIGGER SUIVI_AMITIE_ID_TRG
BEFORE INSERT
ON SUIVI_AMITIE
FOR EACH ROW
BEGIN
    SELECT SUIVI_AMITIE_SEQ.NEXTVAL
    INTO :NEW.IdSuivi
    FROM DUAL;
END;
/
-- triggeur pour SUCCES
CREATE TRIGGER SUIVI_RESEAU_ID_TRG
BEFORE INSERT
ON SUIVI_RESEAU
FOR EACH ROW
BEGIN
    SELECT SUIVI_RESEAU_SEQ.NEXTVAL
    INTO :NEW.IdSuivi
    FROM DUAL;
END;
/













