REM SUPPRESSION DES TRIGGERS

REM TRIGGER DES SEQUENCES

DROP TRIGGER JEU_ID_TRG;
DROP TRIGGER CONTENU_ID_TRG;
DROP TRIGGER SUCCES_ID_TRG;
DROP TRIGGER PERIODE_ID_TRG;
DROP TRIGGER JOUEUR_ID_TRG;
DROP TRIGGER SUIVI_AMITIE_ID_TRG;
DROP TRIGGER SUIVI_RESEAU_ID_TRG;

DROP TRIGGER NOUVEAU_SUCCES_EN_COURS_TRG ;
DROP TRIGGER GENRE_TRG;
DROP TRIGGER SUIVI_RESEAU_TRG ;
DROP TRIGGER SUIVI_ABONNEMENT_RESEAU_TRG ;
DROP TRIGGER SUIVI_AMI_TRG ;
