REM CLÉS PRIMAIRES (PK)

ALTER TABLE JOUEUR
	ADD CONSTRAINT JOUEUR_PK
	PRIMARY KEY (NoJoueur)	
	USING INDEX;

ALTER TABLE ESRB
	ADD CONSTRAINT ESRB_PK
	PRIMARY KEY (Code)	
	USING INDEX;

ALTER TABLE GENRE
	ADD CONSTRAINT GENRE_PK
	PRIMARY KEY (Code)	
	USING INDEX;

ALTER TABLE SOUS_GENRE_JEU
	ADD CONSTRAINT SOUS_GENRE_JEU_PK
	PRIMARY KEY (CodeSousGenre, IdJeu)	
	USING INDEX;

ALTER TABLE JEU
	ADD CONSTRAINT JEU_PK
	PRIMARY KEY (IdJeu)	
	USING INDEX;

ALTER TABLE CONTENU
	ADD CONSTRAINT CONTENU_PK
	PRIMARY KEY (IdContenu)	
	USING INDEX;

ALTER TABLE CONTENU_POSSEDE
	ADD CONSTRAINT CONTENU_POSSEDE_PK
	PRIMARY KEY (IdContenu, NoJoueur)	
	USING INDEX;

ALTER TABLE SUCCES
	ADD CONSTRAINT SUCCES_PK
	PRIMARY KEY (IdSucces)	
	USING INDEX;

ALTER TABLE SUCCES_CALCULE
	ADD CONSTRAINT SUCCES_CALCULE_PK
	PRIMARY KEY (IdSucces)	
	USING INDEX;

ALTER TABLE SUCCES_REALISE
	ADD CONSTRAINT SUCCES_REALISE_PK
	PRIMARY KEY (IdContenu, NoJoueur, IdSucces)	
	USING INDEX;

ALTER TABLE SUCCES_EN_COURS
	ADD CONSTRAINT SUCCES_EN_COURS_PK
	PRIMARY KEY (IdContenu, NoJoueur, IdSucces)	
	USING INDEX;

ALTER TABLE FORFAIT
	ADD CONSTRAINT FORFAIT_PK
	PRIMARY KEY (Code)	
	USING INDEX;

ALTER TABLE PERIODE
	ADD CONSTRAINT PERIODE_PK
	PRIMARY KEY (IdPeriode)	
	USING INDEX;

ALTER TABLE PERIODE_FORFAIT_JOUEUR
	ADD CONSTRAINT PERIODE_FORFAIT_JOUEUR_PK
	PRIMARY KEY (IdPeriode, NoJoueur)
	USING INDEX;

ALTER TABLE RESEAU
	ADD CONSTRAINT RESEAU_PK
	PRIMARY KEY (Code)	
	USING INDEX;

ALTER TABLE ABONNEMENT_RESEAU
	ADD CONSTRAINT ABONNEMENT_RESEAU_PK
	PRIMARY KEY (CodeReseau, NoJoueur)	
	USING INDEX;

ALTER TABLE SUIVI_RESEAU
	ADD CONSTRAINT SUIVI_RESEAU_PK
	PRIMARY KEY (IdSuivi)	
	USING INDEX;

ALTER TABLE AMI
	ADD CONSTRAINT AMI_PK
	PRIMARY KEY (NoJoueurInvitant, NoJoueurInvite)	
	USING INDEX;

ALTER TABLE STATUT_AMITIE
	ADD CONSTRAINT STATUT_AMITIE_PK
	PRIMARY KEY (CodeStatut)	
	USING INDEX;

ALTER TABLE SUIVI_AMITIE
	ADD CONSTRAINT SUIVI_AMITIE_PK
	PRIMARY KEY (IdSuivi)	
	USING INDEX;


REM CLÉS ÉTRANGÈRES (FK)
	
ALTER TABLE GENRE
	ADD CONSTRAINT GENRE_FK
	FOREIGN KEY (CodeGenreParent)
	REFERENCES GENRE (Code);

ALTER TABLE SOUS_GENRE_JEU
	ADD CONSTRAINT SOUS_GENRE_JEU_SOUS_GENRE_FK
	FOREIGN KEY (CodeSousGenre)
	REFERENCES GENRE (Code);

ALTER TABLE SOUS_GENRE_JEU
	ADD CONSTRAINT SOUS_GENRE_JEU_ID_JEU_FK
	FOREIGN KEY (IdJeu)
	REFERENCES JEU (IdJeu);

ALTER TABLE JEU
	ADD CONSTRAINT JEU_CODE_ESRB_FK
	FOREIGN KEY (CodeESRB)
	REFERENCES ESRB (Code);

ALTER TABLE JEU
	ADD CONSTRAINT JEU_CODE_GENRE_FK
	FOREIGN KEY (CodeGenre)
	REFERENCES GENRE (Code);

ALTER TABLE CONTENU
	ADD CONSTRAINT CONTENU_FK
	FOREIGN KEY (IdJeu)
	REFERENCES JEU (IdJeu);

ALTER TABLE CONTENU_POSSEDE
	ADD CONSTRAINT CONTENU_POSSEDE_ID_CONTENU_FK
	FOREIGN KEY (IdContenu)
	REFERENCES Contenu (IdContenu);

ALTER TABLE CONTENU_POSSEDE
	ADD CONSTRAINT CONTENU_POSSEDE_NO_JOUEUR_FK
	FOREIGN KEY (NoJoueur)
	REFERENCES Joueur (NoJoueur);

ALTER TABLE SUCCES
	ADD CONSTRAINT SUCCES_FK
	FOREIGN KEY (IdContenu)
	REFERENCES CONTENU (IdContenu);

ALTER TABLE SUCCES_CALCULE
	ADD CONSTRAINT SUCCES_CALCULE_FK
	FOREIGN KEY (IdSucces)
	REFERENCES SUCCES (IdSucces);

ALTER TABLE SUCCES_REALISE
	ADD CONSTRAINT SUCCES_REALISE_ID_SUCCES_FK
	FOREIGN KEY (IdSucces)
	REFERENCES SUCCES (IdSucces);

ALTER TABLE SUCCES_REALISE
	ADD CONSTRAINT SUCCES_REALISE_CONTENU_FK
	FOREIGN KEY (IdContenu, NoJoueur)
	REFERENCES CONTENU_POSSEDE (IdContenu, NoJoueur);

ALTER TABLE SUCCES_EN_COURS
	ADD CONSTRAINT SUCCES_EN_COURS_ID_SUCCES_FK
	FOREIGN KEY (IdSucces)
	REFERENCES SUCCES_CALCULE (IdSucces);

ALTER TABLE SUCCES_EN_COURS
	ADD CONSTRAINT SUCCES_EN_COURS_CONTENU_FK
	FOREIGN KEY (IdContenu, NoJoueur)
	REFERENCES CONTENU_POSSEDE (IdContenu, NoJoueur);

ALTER TABLE PERIODE
	ADD CONSTRAINT PERIODE_FK
	FOREIGN KEY (CodeForfait)
	REFERENCES FORFAIT (Code);

ALTER TABLE PERIODE_FORFAIT_JOUEUR
	ADD CONSTRAINT PERIODE_FORF_J_ID_PERIODE_FK
	FOREIGN KEY (IdPeriode)
	REFERENCES PERIODE (IdPeriode);

ALTER TABLE PERIODE_FORFAIT_JOUEUR
	ADD CONSTRAINT PERIODE_FORF_J_NO_JOUEUR_FK
	FOREIGN KEY (NoJoueur)
	REFERENCES JOUEUR (NoJoueur);

ALTER TABLE ABONNEMENT_RESEAU
	ADD CONSTRAINT ABONNEMENT_CODE_RESEAU_FK
	FOREIGN KEY (CodeReseau)
	REFERENCES RESEAU (Code);

ALTER TABLE ABONNEMENT_RESEAU
	ADD CONSTRAINT ABONNEMENT_NO_JOUEUR_FK
	FOREIGN KEY (NoJoueur)
	REFERENCES JOUEUR (NoJoueur);

ALTER TABLE SUIVI_RESEAU
	ADD CONSTRAINT SUIVI_RESEAU_CODE_RESEAU_FK
	FOREIGN KEY (CodeReseau)
	REFERENCES RESEAU (Code);

ALTER TABLE SUIVI_RESEAU
	ADD CONSTRAINT SUIVI_RESEAU_NO_JOUEUR_FK
	FOREIGN KEY (NoJoueur)
	REFERENCES JOUEUR (NoJoueur);

ALTER TABLE AMI 
	ADD CONSTRAINT AMI_CODE_STATUT_FK
	FOREIGN KEY (CodeStatut)
	REFERENCES STATUT_AMITIE (CodeStatut);
	
ALTER TABLE AMI
	ADD CONSTRAINT AMI_NO_JOUEUR_INVITANT_FK
	FOREIGN KEY (NoJoueurInvitant)
	REFERENCES JOUEUR (NoJoueur);

ALTER TABLE AMI
	ADD CONSTRAINT AMI_NO_JOUEUR_INVITE_FK
	FOREIGN KEY (NoJoueurInvite)
	REFERENCES JOUEUR (NoJoueur);

ALTER TABLE SUIVI_AMITIE
	ADD CONSTRAINT SUIVI_AMI_NO_J_INVITANT_FK
	FOREIGN KEY (NoJoueurInvitant)
	REFERENCES JOUEUR (NoJoueur);

ALTER TABLE SUIVI_AMITIE
	ADD CONSTRAINT SUIVI_AMI_NO_J_INVITE_FK
	FOREIGN KEY (NoJoueurInvite)
	REFERENCES JOUEUR (NoJoueur);

ALTER TABLE SUIVI_AMITIE
	ADD CONSTRAINT SUIVI_AMITIE_CODE_STATUT_FK
	FOREIGN KEY (CodeStatut)
	REFERENCES STATUT_AMITIE (CodeStatut);


REM Champs UNIQUE

ALTER TABLE JOUEUR
	ADD CONSTRAINT JOUEUR_UNIQUE UNIQUE (Courriel, Surnom);


REM Listes des constraintes (CHECK CONSTRAINT)

ALTER TABLE CONTENU
	ADD CONSTRAINT CHECK_CONTENU_TYPE CHECK (
		TypeContenu IN ('J', 'D', 'O')
	);

ALTER TABLE JOUEUR
	ADD CONSTRAINT CHECK_JOUEUR_ACTIF CHECK (
		Actif IN ('1', '0')
	);

ALTER TABLE RESEAU
	ADD CONSTRAINT CHECK_RESEAU_ACTIF CHECK (
		Actif IN ('1', '0')
	);

ALTER TABLE SUIVI_RESEAU
	ADD CONSTRAINT CHECK_SUIVI_RESEAU_ACTION CHECK (
		Action IN ('CRE', 'SUP', 'ACT', 'DES', 'ABO', 'DSA')
	);
REM 'CREATION RESEAU', 'SUPPRESSION RESEAU', 
REM 'ACTIVATION RESEAU', 'DESACTIVATION RESEAU', 
REM 'ABONNEMENT JOUEUR', 'DESABONNEMENT JOUEUR'

ALTER TABLE SUCCES
	ADD CONSTRAINT CHECK_SUCCES_VALEUR CHECK (Valeur > 0);

ALTER TABLE SUCCES_CALCULE
	ADD CONSTRAINT CHECK_SUCCES_C_MAX_REQUIS CHECK (MaximumRequis > 0);

ALTER TABLE SUCCES_EN_COURS
	ADD CONSTRAINT CHECK_SUCCES_EN_COURS_COMPTEUR CHECK (Compteur > 0);

ALTER TABLE PERIODE
	ADD CONSTRAINT CHECK_PERIODE_PRIX CHECK (Prix >= 0);


REM Valeurs par défaut

ALTER TABLE SUCCES_EN_COURS
  MODIFY (Compteur DEFAULT 0);

ALTER TABLE PERIODE_FORFAIT_JOUEUR
  MODIFY (DateAchat DEFAULT SysDate);

ALTER TABLE JOUEUR
  MODIFY (Actif DEFAULT '1');

ALTER TABLE RESEAU
  MODIFY (Actif DEFAULT '1');

ALTER TABLE RESEAU
  MODIFY (Actif DEFAULT '1');

ALTER TABLE SUIVI_RESEAU
  MODIFY (Moment DEFAULT CURRENT_TIMESTAMP);

ALTER TABLE SUIVI_AMITIE
  MODIFY (Moment DEFAULT CURRENT_TIMESTAMP);


REM Séquences

CREATE SEQUENCE JEU_SEQ; 
CREATE SEQUENCE CONTENU_SEQ;
CREATE SEQUENCE SUCCES_SEQ;
CREATE SEQUENCE PERIODE_SEQ;
CREATE SEQUENCE JOUEUR_SEQ;
CREATE SEQUENCE SUIVI_AMITIE_SEQ;
CREATE SEQUENCE SUIVI_RESEAU_SEQ;