REM SUPPRESSION DES DONNÉES

DELETE FROM SUIVI_AMITIE;
DELETE FROM STATUT_AMITIE;
DELETE FROM AMI;
DELETE FROM SUCCES_REALISE;
DELETE FROM SUCCES_EN_COURS;
DELETE FROM SUCCES_CALCULE;
DELETE FROM SUCCES;
DELETE FROM CONTENU_POSSEDE;
DELETE FROM CONTENU;
DELETE FROM PERIODE_FORFAIT_JOUEUR;
DELETE FROM PERIODE;
DELETE FROM FORFAIT;
DELETE FROM SUIVI_RESEAU;
DELETE FROM ABONNEMENT_RESEAU;
DELETE FROM RESEAU;
DELETE FROM SOUS_GENRE_JEU;
DELETE FROM JOUEUR;
DELETE FROM JEU;
DELETE FROM GENRE;
DELETE FROM ESRB;