REM SUPPRESSION DES TABLES

DROP TABLE JOUEUR;
DROP TABLE ESRB;
DROP TABLE GENRE;
DROP TABLE SOUS_GENRE_JEU;
DROP TABLE JEU;
DROP TABLE CONTENU;
DROP TABLE CONTENU_POSSEDE;
DROP TABLE SUCCES;
DROP TABLE SUCCES_CALCULE;
DROP TABLE SUCCES_REALISE;
DROP TABLE SUCCES_EN_COURS;
DROP TABLE FORFAIT;
DROP TABLE PERIODE;
DROP TABLE PERIODE_FORFAIT_JOUEUR;
DROP TABLE RESEAU;
DROP TABLE ABONNEMENT_RESEAU;
DROP TABLE SUIVI_RESEAU;
DROP TABLE AMI;
DROP TABLE STATUT_AMITIE;
DROP TABLE SUIVI_AMITIE;